import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const SUPABASE_URL='https://myrtdfyjoxvtubusrrmf.supabase.co';
const SUPABASE_KEY='sb_publishable_128ongB0ItsEwmef_F1zTg_YnxFX6M8';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const root=document.getElementById('app');

const state={mode:'artist',playlists:null,curators:null,session:null,submit:{track:null,genre:'',moods:[],selected:[],step:1,results:[]}};
const esc=(v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const slug=(v)=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const norm=(v)=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const nfmt=(n)=>Number.isFinite(Number(n))?new Intl.NumberFormat('en-US',{notation:Number(n)>999?'compact':'standard',maximumFractionDigits:1}).format(Number(n)):'Not confirmed';
const date=(v)=>v?new Date(v).toLocaleDateString():'Unavailable';
const route=()=>location.pathname.replace(/\/+$/,'')||'/';

const articles=[
 ['submit-music-to-spotify-playlists','Submission','spotify playlist submission','How to Submit Music to Spotify Playlists Without Paying for Fake Placement','Start with fit, not follower count. A playlist with a clear editorial identity and an active curator is more useful than a large list that is stale or off-genre.|Prepare one canonical track link, a short pitch, accurate genre and mood tags, and the release context the curator actually needs.|Never treat an acceptance as proof of placement. A credible workflow separates Accepted, Scheduled, Pending Verification, Live and Complete.|Avoid offers that promise guaranteed streams or placement in exchange for payment or forced engagement.'],
 ['playlist-submission-scams','Safety','playlist submission scam','Spotify Playlist Submission Scams: Red Flags, Safe Alternatives, and What to Check','Guaranteed streams, guaranteed placement and pressure to pay immediately are high-risk signals.|Look for editorial identity, clear submission rules, transparent ownership or claim evidence, and a history that can be explained.|Follower count alone is not proof of quality. Use multiple signals and label uncertainty rather than declaring a playlist fraudulent from one metric.'],
 ['submithub-alternatives','Comparison','SubmitHub alternatives','Best SubmitHub Alternatives for Independent Artists','Some platforms sell guaranteed feedback, some sell campaign management, and some provide free curator directories. Those are different products.|Compare targeting control, curator accountability, response visibility, safety signals and what happens after an acceptance.|CuratorOS is designed around one canonical submission, independent playlist routes and evidence-backed placement status.'],
 ['playlist-pitch-template','Pitching','playlist pitch template','Playlist Pitch Template: What Curators Actually Need to Hear','Lead with the track, the relevant genre or mood, and one sentence explaining why it fits that specific playlist.|Add release timing or a focus timestamp only when it helps the curator make a decision.|Do not ask for guaranteed placement, streams or follower swaps.'],
 ['find-playlists-for-my-music','Discovery','find Spotify playlists for my music','How to Find Playlists That Actually Fit Your Music','Define the track with a controlled genre and a few meaningful moods.|Compare that profile to each playlist’s declared lane, current criteria and recent activity.|A Long shot can still be eligible. The point is to explain the mismatch before the artist spends attention on it.'],
 ['find-legitimate-spotify-curators','Trust','Spotify playlist curators','How to Find Legitimate Spotify Playlist Curators','A curator account can be approved without every playlist being verified. A playlist claim can be verified without implying endorsement of every editorial decision.|Look for ownership or management evidence, public criteria, consistent identity and a transparent submission process.'],
 ['playlist-promotion-plan','Release strategy','playlist promotion','Playlist Promotion for Independent Artists: A Practical Release Plan','Use pre-release planning for assets, positioning and target research.|On release week, combine playlist outreach with fan communication, creator content and owned-audience capture.|Measure source to submission to decision rather than treating every playlist add as equal.'],
 ['music-submission-checklist','Tools','music submission checklist','The Music Submission Checklist: Is Your Release Ready for Curators?','Confirm the track identity, artwork, release date, explicit flag and clean canonical link.|Choose a controlled genre and a few specific moods.|Write a short pitch and verify that every selected playlist is actually accepting submissions.'],
 ['submit-music-to-edm-playlists','Genre','submit music to EDM playlists','How to Submit Music to EDM Playlists: Genre Fit, Pitching, and Safety','Break electronic music into useful lanes such as melodic bass, future bass, chillstep, house and drum and bass.|Use mood and energy language to refine fit, then check the curator’s specific rules.|Do not infer quality from follower count alone.'],
 ['playlist-submission-management','Curators','playlist submission management','How to Run a Playlist Submission Process Without Drowning in DMs','Define structured criteria before opening the inbox.|Keep one route per playlist so decisions stay independent.|Use hold dates, decline reasons and a real placement lifecycle so the queue never lies about what happened.']
].map(([slug,category,keyword,title,body])=>({slug,category,keyword,title,body:body.split('|')}));

function chrome(content){
 const artist=[['Discover','/playlists'],['Submit Music','/submit'],['Playlists','/playlists'],['Curators','/curators'],['Genres','/genres'],['Free Tools','/tools'],['Learn','/learn']];
 const curator=[['Inbox','/app/inbox'],['Playlists','/playlists'],['Placements','/app/inbox#placements'],['Analytics','/app/inbox#analytics'],['Profile','/apply']];
 const nav=state.mode==='artist'?artist:curator;
 return '<div class="statusbar"><span>SYSTEM</span><strong>Canonical backend: ArtistOS / Playlist OS / CuratorOS</strong><span class="status-accent">Founding beta</span></div>'+
 '<header class="site-header"><div class="nav-shell"><div class="brand">CuratorOS</div><span class="spec-pill">BETA</span>'+
 '<div class="mode-toggle"><button data-mode="artist" class="'+(state.mode==='artist'?'active':'')+'">Artist</button><button data-mode="curator" class="'+(state.mode==='curator'?'active':'')+'">Curator</button></div>'+
 '<nav class="nav-links">'+nav.map(([l,h])=>'<a data-link href="'+h+'">'+l+'</a>').join('')+'</nav>'+
 '<div class="nav-actions"><a data-link class="button dark small" href="/submit">Submit Music</a><a data-link class="button small outline desktop" href="/apply">Apply as Curator</a></div></div></header>'+
 content+
 '<footer class="footer"><div class="shell footer-grid"><div><div class="brand big">CuratorOS</div><p>Neutral playlist submission infrastructure. BVSS FVM is Verified Network #001.</p></div><div><strong>Artists</strong><a data-link href="/submit">Submit music</a><a data-link href="/playlists">Discover playlists</a><a data-link href="/tools">Free tools</a></div><div><strong>Curators</strong><a data-link href="/apply">Apply as curator</a><a data-link href="/app/inbox">Inbox</a><a data-link href="/learn/playlist-submission-management">Operations guide</a></div><div><strong>Principles</strong><span>No guaranteed placement</span><span>Independent decisions</span><span>Evidence-backed status</span></div></div></footer>';
}
function pageHero(kicker,title,copy){return '<section class="page-hero"><div class="shell"><div class="eyebrow">'+esc(kicker)+'</div><h1>'+title+'</h1><p>'+esc(copy)+'</p></div></section>'}
function chips(values){return '<div class="chips">'+(values||[]).slice(0,6).map(x=>'<span class="chip">'+esc(x)+'</span>').join('')+'</div>'}
function playlistCard(p){
 const img=p.cover_asset_url?'<img src="'+esc(p.cover_asset_url)+'" alt="">':esc((p.canonical_name||'PL').slice(0,2).toUpperCase());
 return '<article class="playlist-card"><div class="cover">'+img+'</div><div class="playlist-body"><div class="eyebrow-row"><span>'+(p.network_owner_type==='bvss'?'BVSS FVM · Network #001':'Independent curator')+'</span>'+(p.verification_status==='verified'?'<b class="verified">Verified claim</b>':'')+'</div><h3><a data-link href="/playlists/'+esc(p.slug)+'">'+esc(p.canonical_name)+'</a></h3><p>'+esc(p.subtitle||p.description||'Independent playlist')+'</p>'+chips([p.primary_genre,...(p.moods||[]).slice(0,2)])+'<div class="metric-row"><div><small>Followers</small><strong>'+nfmt(p.current_follower_count)+'</strong></div><div><small>Tracks</small><strong>'+esc(p.current_track_count??'—')+'</strong></div><div><small>Submissions</small><strong>'+(p.submission_status==='open'?'Open':'Paused')+'</strong></div></div></div></article>';
}
async function getPlaylists(force=false){
 if(state.playlists&&!force)return state.playlists;
 const r=await fetch('/api/playlists');const b=await r.json();state.playlists=(b.playlists||[]);return state.playlists;
}
async function getCurators(force=false){
 if(state.curators&&!force)return state.curators;
 const r=await fetch('/api/curators');const b=await r.json();state.curators=(b.curators||[]);return state.curators;
}
function fit(p,genre,moods=[],comp=[]){
 let strength=0,reasons=[],caveats=[];const g=norm(genre),primary=norm(p.primary_genre),secondary=(p.secondary_genres||[]).map(norm);
 if(primary===g){strength+=3;reasons.push('Primary genre aligns: '+p.primary_genre)}else if(secondary.includes(g)){strength+=2;reasons.push('Genre appears in this playlist’s secondary lanes')}else if(g&&[primary,...secondary].some(x=>x.includes(g)||g.includes(x))){strength+=1;reasons.push('Related genre lane')}else caveats.push('Genre may be outside the main lane');
 const pm=(p.moods||[]).map(norm),hits=moods.filter(m=>pm.includes(norm(m)));if(hits.length){strength+=Math.min(2,hits.length);reasons.push('Mood overlap: '+hits.slice(0,3).join(', '))}else if(moods.length)caveats.push('No exact mood overlap in the current profile');
 const pa=(p.anchor_artists||[]).map(norm),ah=comp.filter(a=>pa.includes(norm(a)));if(ah.length){strength+=2;reasons.push('Comparable-artist overlap: '+ah.slice(0,2).join(', '))}
 const band=strength>=5?'Strong fit':strength>=3?'Worth a look':strength>=1?'Long shot':'No band';
 return {band,strength,reasons:reasons.slice(0,3),caveats:caveats.slice(0,2)};
}
function fitBadge(b){return '<span class="fit-badge '+slug(b)+'">'+esc(b)+'</span>'}

async function home(){
 const ps=(await getPlaylists()).filter(p=>p.lifecycle_state==='active'&&p.verification_status==='verified');
 const active=ps.filter(p=>p.submission_status==='open');const measured=active.filter(p=>Number.isFinite(Number(p.current_follower_count)));const reach=measured.reduce((s,p)=>s+Number(p.current_follower_count||0),0);
 return '<main><section class="hero"><div class="shell hero-grid"><div><div class="network-pill"><span class="pulse"></span>BVSS FVM — Powered by CuratorOS · Verified Network #001</div><h1>Submit once.<br><em>Reach the right</em><br>playlists.</h1><p class="hero-copy">CuratorOS is the neutral marketplace connecting independent artists with real playlist curators. One canonical submission. Independent playlist decisions. Every status change tracked.</p><div class="hero-search"><input id="hero-search" placeholder="Search artist + track, or paste a Spotify track URL"><button id="hero-go">Find my fit →</button></div><div class="statgrid"><div><small>Verified networks</small><strong>1</strong></div><div><small>Active playlists</small><strong>'+active.length+'</strong></div><div><small>Measured reach</small><strong>'+(reach?nfmt(reach):'Pending')+'</strong></div></div></div><aside class="hero-side"><div class="panel"><div class="eyebrow">For artists</div><h3>One song. Clear routing.</h3><p>See why a playlist may fit before you submit. Track each curator decision separately.</p><a data-link class="button acid" href="/submit">Submit music</a></div><div class="panel"><div class="eyebrow">For curators</div><h3>Better submissions. Less inbox chaos.</h3><p>Define your lane, review quickly, schedule placements and keep status honest.</p><a data-link class="button" href="/apply">Apply as curator</a></div></aside></div></section>'+
 '<section class="section"><div class="shell"><div class="section-head"><div><div class="eyebrow">How it works</div><h2>Complex underneath. Simple outside.</h2></div><p>One canonical submission fans out only to selected or explicitly opted-in playlist routes. Every route can reach a different decision.</p></div><div class="grid3"><div class="tile"><span class="tile-number">01</span><h3>Find the track</h3><p>Search artist + song or paste a Spotify track link. We resolve the canonical track identity.</p></div><div class="tile"><span class="tile-number">02</span><h3>See the fit</h3><p>Strong fit, Worth a look, Long shot — with visible reasons and caveats, never an opaque score.</p></div><div class="tile"><span class="tile-number">03</span><h3>Track every route</h3><p>Acceptance is not a Live placement. Scheduled, Pending Verification and Live remain separate states.</p></div></div></div></section>'+
 '<section class="section"><div class="shell"><div class="section-head"><div><div class="eyebrow">Verified supply</div><h2>Playlists accepting music now.</h2></div><a data-link class="button" href="/playlists">Explore all playlists</a></div><div class="playlist-grid">'+active.slice(0,6).map(playlistCard).join('')+'</div></div></section>'+
 '<section class="section black-section"><div class="shell"><div class="section-head"><div><div class="eyebrow">Traffic engine</div><h2>Free tools that lead somewhere useful.</h2></div><p>Each tool solves a real problem first, then gives the user a relevant next action inside CuratorOS.</p></div><div class="tool-grid">'+toolCards()+'</div></div></section></main>';
}
function toolCards(){return [
 ['playlist-fit-finder','Playlist Fit Finder','Paste a track and see which live playlists align — with evidence.'],
 ['playlist-safety-checker','Playlist Safety Signals','Review claim and freshness signals without unsupported “scam” verdicts.'],
 ['playlist-pitch-generator','Pitch Generator','Create concise, playlist-specific pitch copy.'],
 ['genre-mood-finder','Genre / Mood Finder','Use the same controlled vocabulary as routing.'],
 ['submission-readiness-checker','Readiness Checker','Fix missing basics before a curator sees the pitch.'],
 ['learn','Learn','Guides, comparisons, safety and curator operations.']
].map(([s,t,d])=>'<div class="tool-card"><h3>'+t+'</h3><p>'+d+'</p><a data-link href="'+(s==='learn'?'/learn':'/tools/'+s)+'">Open →</a></div>').join('')}

async function playlistsPage(){
 const ps=(await getPlaylists()).filter(p=>p.lifecycle_state==='active'&&p.verification_status==='verified');
 const genres=[...new Set(ps.flatMap(p=>[p.primary_genre,...(p.secondary_genres||[])]))].sort();
 return '<main>'+pageHero('Discover','Verified playlists.','Browse real playlist supply with declared genres, moods and submission state. Follower count is context, not a quality verdict.')+'<section class="section"><div class="shell"><div class="filterbar" id="genre-filters"><button class="active" data-genre="">All</button>'+genres.slice(0,20).map(g=>'<button data-genre="'+esc(g)+'">'+esc(g)+'</button>').join('')+'</div><div class="playlist-grid" id="playlist-grid">'+ps.map(playlistCard).join('')+'</div></div></section></main>';
}
async function playlistDetail(slugValue){
 const ps=await getPlaylists();const p=ps.find(x=>x.slug===slugValue);if(!p)return notFound();
 return '<main>'+pageHero(p.network_owner_type==='bvss'?'BVSS FVM · Verified Network #001':'Independent curator',esc(p.canonical_name),p.description||p.subtitle||'Independent playlist')+
 '<section class="section"><div class="shell detail-grid"><div><div class="detail-card"><h2>What this playlist wants</h2>'+chips([p.primary_genre,...(p.secondary_genres||[]),...(p.moods||[])])+'<p>'+esc(p.submission_criteria||'Submission criteria are being refined from the curator’s declared lane.')+'</p><p class="provenance">Claim status: '+esc(p.verification_status)+'. Metadata last updated: '+date(p.updated_at)+'.</p></div><div class="detail-card" style="margin-top:18px"><h2>Editorial identity</h2><p>'+esc(p.curation_philosophy||'Independent editorial judgment. Placement is never guaranteed or sold.')+'</p></div></div><aside class="detail-card"><div class="eyebrow">Submit</div><h2>Check your track’s fit.</h2><p>Start with your canonical track. CuratorOS will show visible reasons before you submit.</p><a data-link class="button dark" href="/submit?playlist='+encodeURIComponent(p.slug)+'">Submit to this playlist</a><a class="button" target="_blank" rel="noreferrer" style="margin-top:8px" href="'+esc(p.spotify_url)+'">Open on Spotify</a></aside></div></section></main>';
}
async function curatorsPage(){
 const cs=await getCurators();
 return '<main>'+pageHero('People behind the playlists','Curators.','Approved curator accounts and their verified playlist claims. Identity approval, playlist verification and network membership are separate trust signals.')+'<section class="section"><div class="shell"><div class="article-grid">'+(cs.length?cs.map(c=>'<article class="article-card"><div class="eyebrow">Approved curator</div><h3><a data-link href="/curators/'+esc(c.handle)+'">'+esc(c.display_name)+'</a></h3><p>'+esc(c.bio||'Independent playlist curator.')+'</p>'+chips((c.genres||[]).slice(0,4))+'<p class="provenance">Verified playlist claims: '+esc(c.verified_playlist_count??0)+'</p></article>').join(''):'<div class="notice">Founding curator applications are open. Public profiles appear only after approval and verified playlist claims.</div>')+'</div></div></section></main>';
}
async function curatorDetail(handle){
 const r=await fetch('/api/curators?handle='+encodeURIComponent(handle));if(!r.ok)return notFound();const d=await r.json(),c=d.curator;
 return '<main>'+pageHero('Approved curator',esc(c.display_name),c.bio||'Independent curator on CuratorOS.')+'<section class="section"><div class="shell"><div class="section-head"><div><div class="eyebrow">Verified claims</div><h2>Playlists managed</h2></div><p>Playlist verification does not imply guaranteed placement or endorsement of every editorial decision.</p></div><div class="playlist-grid">'+(d.playlists||[]).map(playlistCard).join('')+'</div></div></section></main>';
}
async function genresPage(){
 const ps=(await getPlaylists()).filter(p=>p.lifecycle_state==='active');const counts={};ps.forEach(p=>[p.primary_genre,...(p.secondary_genres||[])].forEach(g=>counts[g]=(counts[g]||0)+1));
 const rows=Object.entries(counts).sort((a,b)=>b[1]-a[1]);
 return '<main>'+pageHero('Controlled taxonomy','Genres.','Genre pages are generated from real playlist supply rather than uncontrolled SEO tags.')+'<section class="section"><div class="shell article-grid">'+rows.map(([g,n])=>'<article class="article-card"><div class="eyebrow">'+n+' active playlist'+(n===1?'':'s')+'</div><h3><a data-link href="/genres/'+slug(g)+'">'+esc(g)+'</a></h3><p>Explore verified playlists, related moods and submission guidance for '+esc(g)+'.</p></article>').join('')+'</div></section></main>';
}
async function genreDetail(gslug){
 const ps=(await getPlaylists()).filter(p=>p.lifecycle_state==='active'&&[p.primary_genre,...(p.secondary_genres||[])].some(g=>slug(g)===gslug));const name=ps.flatMap(p=>[p.primary_genre,...(p.secondary_genres||[])]).find(g=>slug(g)===gslug)||gslug.replace(/-/g,' ');const moods=[...new Set(ps.flatMap(p=>p.moods||[]))].slice(0,14);
 return '<main>'+pageHero('Genre hub',esc(name),ps.length+' current playlist'+(ps.length===1?'':'s')+' in the CuratorOS supply graph use this lane. Availability changes as curators update criteria.')+'<section class="section"><div class="shell">'+chips(moods)+'<div class="section-head"><h2>Playlists in this lane</h2><a data-link class="button dark" href="/submit?genre='+encodeURIComponent(name)+'">Submit a '+esc(name)+' track</a></div><div class="playlist-grid">'+ps.map(playlistCard).join('')+'</div></div></section></main>';
}
function learnPage(){
 return '<main>'+pageHero('CuratorOS Learn','Useful answers, not filler.','Submission strategy, curator operations, safety and platform comparisons designed to lead into a real next action.')+'<section class="section"><div class="shell article-grid">'+articles.map(a=>'<article class="article-card"><div class="eyebrow">'+esc(a.category)+' · '+esc(a.keyword)+'</div><h3><a data-link href="/learn/'+a.slug+'">'+esc(a.title)+'</a></h3><p>'+esc(a.body[0])+'</p></article>').join('')+'</div></section></main>';
}
function articlePage(aslug){
 const a=articles.find(x=>x.slug===aslug);if(!a)return notFound();
 return '<main>'+pageHero(a.category+' · Target: '+a.keyword,esc(a.title),a.body[0])+'<section class="section"><div class="shell article-body">'+a.body.map(p=>'<p>'+esc(p)+'</p>').join('')+'<div class="notice">CuratorOS never promises placement. Use fit evidence and curator criteria to decide where your track is genuinely worth submitting.</div><p><a data-link class="button dark" href="/submit">Paste your track →</a></p></div></section></main>';
}
function toolsPage(){return '<main>'+pageHero('Free tools','Useful before you submit.','Each tool solves a real problem first, then offers a relevant CuratorOS next step.')+'<section class="section"><div class="shell tool-grid">'+toolCards().replace('/learn','/learn')+'</div></section></main>'}

async function toolPage(tslug){
 const ps=(await getPlaylists()).filter(p=>p.lifecycle_state==='active'&&p.verification_status==='verified');
 const genres=[...new Set(ps.flatMap(p=>[p.primary_genre,...(p.secondary_genres||[])]))].sort();const moods=[...new Set(ps.flatMap(p=>p.moods||[]))].sort();
 const names={
  'playlist-fit-finder':['Playlist Fit Finder','See where a track may fit before you submit.'],
  'playlist-safety-checker':['Playlist Safety Signals','Review the evidence CuratorOS has without unsupported scam verdicts.'],
  'playlist-pitch-generator':['Playlist Pitch Generator','Write short, specific curator-ready copy.'],
  'genre-mood-finder':['Genre / Mood Finder','Use the controlled language that powers routing.'],
  'submission-readiness-checker':['Submission Readiness Checker','Fix missing basics before a curator sees the pitch.']
 };if(!names[tslug])return notFound();const [title,desc]=names[tslug];
 let body='';
 if(tslug==='playlist-fit-finder')body='<div class="tool-shell"><div class="detail-card"><div class="field"><label>Track</label><div class="hero-search" style="margin-top:0"><input id="tool-track" placeholder="Artist + track or Spotify URL"><button id="tool-recognize">Recognize</button></div></div><div class="field" style="margin-top:14px"><label>Primary genre</label><select id="tool-genre"><option value="">Choose…</option>'+genres.map(g=>'<option>'+esc(g)+'</option>').join('')+'</select></div><div class="field" style="margin-top:14px"><label>Moods</label><div class="chips" id="tool-moods">'+moods.slice(0,30).map(m=>'<button type="button" class="chip" data-mood="'+esc(m)+'">'+esc(m)+'</button>').join('')+'</div></div><div class="route-list" id="fit-results" style="margin-top:18px"></div></div><aside class="tool-result"><h3>Your next action</h3><p id="tool-message">Describe the track using the same controlled vocabulary CuratorOS uses for routing.</p><a data-link class="button dark" href="/submit">Open submission flow</a></aside></div>';
 if(tslug==='playlist-safety-checker')body='<div class="tool-shell"><div class="detail-card"><h2>Playlist safety signals.</h2><p>This does not label a playlist fake or safe. It shows the evidence CuratorOS actually has.</p><div class="field"><label>Known CuratorOS playlist</label><select id="safety-playlist"><option value="">Choose…</option>'+ps.map(p=>'<option value="'+esc(p.slug)+'">'+esc(p.canonical_name)+'</option>').join('')+'</select></div></div><aside class="tool-result" id="safety-result"><h3>Evidence, not verdicts.</h3><p>No single signal proves bot activity. Unknown data remains unknown.</p></aside></div>';
 if(tslug==='playlist-pitch-generator')body='<div class="tool-shell"><div class="detail-card"><div class="field"><label>Track</label><input id="pitch-track" placeholder="Track title — Artist"></div><div class="field" style="margin-top:12px"><label>Target playlist</label><select id="pitch-playlist"><option value="">Choose…</option>'+ps.filter(p=>p.submission_status==='open').map(p=>'<option value="'+esc(p.slug)+'">'+esc(p.canonical_name)+'</option>').join('')+'</select></div><button class="button dark" id="pitch-go" style="margin-top:16px">Generate pitch</button></div><aside class="tool-result"><h3>Pitch draft</h3><p id="pitch-output">The generator uses the target playlist’s declared editorial lane instead of generic flattery.</p><button class="button" id="pitch-copy">Copy</button></aside></div>';
 if(tslug==='genre-mood-finder')body='<div class="tool-shell"><div class="detail-card"><h2>Use the routing vocabulary.</h2><div class="field"><label>Primary genre</label><select id="gm-genre"><option value="">Choose…</option>'+genres.map(g=>'<option>'+esc(g)+'</option>').join('')+'</select></div><div class="chips" id="gm-moods">'+moods.slice(0,30).map(m=>'<button class="chip" type="button" data-mood="'+esc(m)+'">'+esc(m)+'</button>').join('')+'</div></div><aside class="tool-result"><h3>Canonical tags</h3><p id="gm-output">Choose the closest genre and a few moods.</p><a data-link class="button dark" href="/submit">Use in submission</a></aside></div>';
 if(tslug==='submission-readiness-checker')body='<div class="tool-shell"><div class="detail-card"><div class="form-grid"><div class="field"><label>Spotify track URL</label><input id="ready-track"></div><div class="field"><label>Release date</label><input id="ready-date" type="date"></div><div class="field"><label>Genre selected?</label><select id="ready-genre"><option value="">No</option><option>Yes</option></select></div><div class="field"><label>Pitch under 300 chars?</label><select id="ready-pitch"><option value="">No</option><option>Yes</option></select></div></div><button id="ready-go" class="button dark" style="margin-top:16px">Check readiness</button></div><aside class="tool-result"><h3 id="ready-score">0/4 essentials ready</h3><p id="ready-output">Complete the pre-flight before submitting.</p></aside></div>';
 return '<main>'+pageHero('Free tool',title,desc)+'<section class="section"><div class="shell">'+body+'</div></section></main>';
}

async function submitPage(){
 const ps=(await getPlaylists()).filter(p=>p.lifecycle_state==='active'&&p.verification_status==='verified'&&p.submission_status==='open'&&p.network_routing_enabled);
 const genres=[...new Set(ps.flatMap(p=>[p.primary_genre,...(p.secondary_genres||[])]))].sort();const moods=[...new Set(ps.flatMap(p=>p.moods||[]))].sort();
 const qs=new URLSearchParams(location.search);if(qs.get('genre'))state.submit.genre=genres.find(g=>norm(g)===norm(qs.get('genre')))||state.submit.genre;if(qs.get('playlist')&&!state.submit.selected.includes(qs.get('playlist')))state.submit.selected=[qs.get('playlist')];
 return '<main>'+pageHero('Universal submission','Find the song. See the fit. Submit once.','Released tracks use a canonical Spotify identity. You choose the routes. Every playlist decision stays independent.')+'<section class="section"><div class="shell detail-grid"><div class="detail-card"><div class="stepbar"><span class="'+(state.submit.step===1?'active':'')+'">1 Track</span><span class="'+(state.submit.step===2?'active':'')+'">2 Fit</span><span class="'+(state.submit.step===3?'active':'')+'">3 Submit</span></div><div id="submit-stage">'+submitStage(ps,genres,moods)+'</div><div id="submit-message"></div></div><aside class="detail-card"><div class="eyebrow">Why this is different</div><h2>No black-box blast.</h2><p>You see each route before submitting. Fit labels are evidence judgments, not opaque percentages. Acceptance starts a placement workflow; it does not create a fake Live placement.</p></aside></div></section></main>';
}
function submitStage(ps,genres,moods){
 if(state.submit.step===1)return '<div class="eyebrow">Canonical track search</div><h2>Find the exact song.</h2><div class="hero-search" style="margin-top:18px"><input id="submit-q" value="'+esc(new URLSearchParams(location.search).get('q')||'')+'" placeholder="Artist + song or Spotify track URL"><button id="submit-search">Search</button></div><div id="submit-results" class="route-list" style="margin-top:18px"></div>';
 if(state.submit.step===2&&state.submit.track){const ranked=state.submit.genre?ps.map(p=>({p,f:fit(p,state.submit.genre,state.submit.moods,[])})).filter(x=>x.f.strength>0).sort((a,b)=>b.f.strength-a.f.strength).slice(0,10):[];return '<div class="eyebrow">Fit & routing</div><h2>'+esc(state.submit.track.title)+'</h2><p>'+esc(state.submit.track.artist_name)+' · '+esc(state.submit.track.release_date||'release date unavailable')+'</p><div class="field"><label>Primary genre</label><select id="submit-genre"><option value="">Choose approved genre…</option>'+genres.map(g=>'<option '+(g===state.submit.genre?'selected':'')+'>'+esc(g)+'</option>').join('')+'</select></div><div class="field" style="margin-top:12px"><label>Moods</label><div class="chips" id="submit-moods">'+moods.slice(0,30).map(m=>'<button type="button" class="chip '+(state.submit.moods.includes(m)?'active':'')+'" data-mood="'+esc(m)+'">'+esc(m)+'</button>').join('')+'</div></div><div class="route-list" style="margin-top:18px">'+ranked.map(({p,f})=>'<label class="route-card"><input type="checkbox" data-route="'+esc(p.slug)+'" '+(state.submit.selected.includes(p.slug)?'checked':'')+'><div><h3>'+esc(p.canonical_name)+'</h3><div class="provenance">'+(p.network_owner_type==='bvss'?'BVSS FVM · #001':'Independent curator')+'</div><ul>'+f.reasons.map(r=>'<li>'+esc(r)+'</li>').join('')+f.caveats.map(r=>'<li>Caveat: '+esc(r)+'</li>').join('')+'</ul></div>'+fitBadge(f.band)+'</label>').join('')+'</div><button id="submit-next" class="button dark" style="margin-top:18px" '+(!state.submit.genre||!state.submit.selected.length?'disabled':'')+'>Continue with '+state.submit.selected.length+' route'+(state.submit.selected.length===1?'':'s')+' →</button>';
 if(state.submit.step===3&&state.submit.track)return '<div class="eyebrow">Review & submit</div><h2>One submission. '+state.submit.selected.length+' independent routes.</h2><div class="form-grid"><div class="field"><label>Artist name</label><input id="submit-artist" value="'+esc(state.submit.track.artist_name||'')+'"></div><div class="field"><label>Email</label><input id="submit-email" type="email"></div><div class="field full"><label>Pitch note (optional)</label><textarea id="submit-notes" placeholder="One or two useful sentences for the curator."></textarea></div></div><div class="notice" style="margin:18px 0">Submission is free. Curators decide independently. A submission never buys or guarantees placement.</div><button class="button dark" id="submit-final">Submit to selected playlists</button>';
 return '';
}

async function statusPage(){
 const token=new URLSearchParams(location.search).get('token')||'';if(!token)return '<main>'+pageHero('Private artist status','Track every decision.','One submission can have different outcomes on different playlists.')+'<section class="section"><div class="shell"><div class="notice error">Missing private status token.</div></div></section></main>';
 const r=await fetch('/api/status?token='+encodeURIComponent(token));if(!r.ok)return '<main>'+pageHero('Private artist status','Status unavailable.','The token may be invalid or expired.')+'</main>';const d=await r.json();
 return '<main>'+pageHero('Private artist status',esc(d.submission.song_title),d.submission.artist_name+' · '+(d.submission.display_status||d.submission.status))+'<section class="section"><div class="shell"><table class="status-table"><thead><tr><th>Playlist</th><th>Network</th><th>Route</th><th>Decision</th></tr></thead><tbody>'+(d.routes||[]).map(x=>'<tr><td>'+esc(x.playlist_name)+'</td><td>'+(x.network_owner_type==='partner'?'Independent curator':'BVSS FVM · #001')+'</td><td>'+esc(x.status)+'</td><td>'+esc(x.decision||'No decision yet')+'</td></tr>').join('')+'</tbody></table><div class="detail-card" style="margin-top:20px"><div class="eyebrow">Timeline</div>'+(d.events||[]).map(e=>'<p><strong>'+esc(e.public_label)+'</strong><br><span class="provenance">'+esc(e.public_detail||'')+' · '+esc(new Date(e.created_at).toLocaleString())+'</span></p>').join('')+'</div></div></section></main>';
}
async function applyPage(){
 const {data}=await supabase.auth.getSession();state.session=data.session;
 return '<main>'+pageHero('Founding Curator Beta','Better submissions. Faster review.','Apply to CuratorOS as an independent curator. BVSS FVM is Verified Network #001, not the owner of your profile or editorial decisions.')+'<section class="section"><div class="shell" id="curator-root">'+(state.session?'<div class="auth-card">Loading curator workspace…</div>':authForm())+'</div></section></main>';
}
function authForm(){return '<div class="auth-card"><div class="eyebrow">Curator account</div><h2>Sign in or create an account.</h2><div class="form-grid"><div class="field full"><label>Email</label><input id="auth-email" type="email"></div><div class="field full"><label>Password</label><input id="auth-password" type="password"></div></div><div style="display:flex;gap:8px;margin-top:16px"><button id="auth-signin" class="button dark">Sign in</button><button id="auth-signup" class="button">Create account</button></div><div id="auth-message"></div></div>'}
async function curatorWorkspace(mode='apply'){
 if(!state.session)return authForm();const r=await fetch('/api/curator',{headers:{Authorization:'Bearer '+state.session.access_token}});const d=await r.json();
 if(!r.ok)return '<div class="notice error">'+esc(d.error||'Curator workspace unavailable')+'</div>';
 if(mode==='apply'&&!d.profile)return '<div class="auth-card"><div class="eyebrow">Step 1 · curator identity</div><h2>Apply to the Founding Curator Beta.</h2><div class="form-grid"><div class="field"><label>Display name</label><input id="apply-name"></div><div class="field"><label>Handle</label><input id="apply-handle"></div><div class="field full"><label>Editorial bio</label><textarea id="apply-bio"></textarea></div><div class="field full"><label>Genres (comma separated)</label><input id="apply-genres" placeholder="future bass, melodic dubstep"></div></div><button id="apply-submit" class="button dark" style="margin-top:16px">Submit application</button><div id="apply-message"></div></div>';
 if(mode==='apply')return '<div class="detail-grid"><div class="detail-card"><div class="eyebrow">Application</div><h2>'+esc(d.profile.display_name)+'</h2><p>Status: <strong>'+esc(d.profile.status)+'</strong></p><p>'+esc(d.profile.bio||'')+'</p><div class="notice">CuratorOS is neutral infrastructure. You are not joining BVSS FVM.</div></div><aside class="detail-card"><div class="eyebrow">Add a playlist</div><h2>Claim supply.</h2><div class="field"><label>Spotify playlist URL</label><input id="claim-url"></div><div class="field"><label>Playlist name</label><input id="claim-name"></div><div class="field"><label>Primary genre</label><input id="claim-genre"></div><button id="claim-add" class="button dark" style="margin-top:14px">Add playlist</button><div id="claim-message"></div><p class="provenance">Description-token verification is available in the current beta path. Spotify owner OAuth remains the preferred ownership proof as the external-curator connection is generalized.</p></aside>';
 const routes=d.routes||[];return '<div><div class="section-head"><div><div class="eyebrow">Curator workspace</div><h2>Inbox</h2></div><span class="provenance">Account: '+esc(d.profile?.status||'unknown')+'</span></div>'+(routes.length?routes.map(r=>'<article class="inbox-card"><div class="eyebrow-row"><span>'+esc(r.bvss_playlists?.canonical_name||'Playlist')+'</span><span>'+esc(r.status)+'</span></div><h3>'+esc(r.bvss_submissions?.song_title||'Submission')+' — '+esc(r.bvss_submissions?.artist_name||'Artist')+'</h3>'+(r.fit_band?fitBadge(r.fit_band):'')+chips((r.fit?.reasons||r.match_reasons||[]).map(x=>typeof x==='string'?x:(x.label||'Fit evidence')).slice(0,3))+'<div style="display:flex;gap:8px;margin-top:14px"><button class="button dark small curator-decision" data-route="'+esc(r.id)+'" data-decision="accept">Accept</button><button class="button small curator-decision" data-route="'+esc(r.id)+'" data-decision="hold">Hold</button><button class="button small curator-decision" data-route="'+esc(r.id)+'" data-decision="reject">Decline</button></div></article>').join(''):'<div class="detail-card">No assigned routes yet.</div>')+'</div>';
}
async function inboxPage(){const {data}=await supabase.auth.getSession();state.session=data.session;return '<main>'+pageHero('Curator workspace','Inbox.','Each playlist route is independent. Accepting one route never accepts the submission everywhere.')+'<section class="section"><div class="shell" id="curator-root">'+(state.session?await curatorWorkspace('inbox'):authForm())+'</div></section></main>'}
function notFound(){return '<main>'+pageHero('404','Not found.','That CuratorOS page does not exist.')+'<section class="section"><div class="shell"><a data-link class="button dark" href="/">Back home</a></div></section></main>'}

async function render(){
 root.innerHTML=chrome('<main><section class="section"><div class="shell">Loading CuratorOS…</div></section></main>');window.scrollTo(0,0);
 const p=route();let content;
 try{
  if(p==='/')content=await home();
  else if(p==='/playlists')content=await playlistsPage();
  else if(p.startsWith('/playlists/'))content=await playlistDetail(decodeURIComponent(p.split('/')[2]));
  else if(p==='/curators')content=await curatorsPage();
  else if(p.startsWith('/curators/'))content=await curatorDetail(decodeURIComponent(p.split('/')[2]));
  else if(p==='/genres')content=await genresPage();
  else if(p.startsWith('/genres/'))content=await genreDetail(decodeURIComponent(p.split('/')[2]));
  else if(p==='/submit')content=await submitPage();
  else if(p==='/tools')content=toolsPage();
  else if(p.startsWith('/tools/'))content=await toolPage(p.split('/')[2]);
  else if(p==='/learn')content=learnPage();
  else if(p.startsWith('/learn/'))content=articlePage(p.split('/')[2]);
  else if(p==='/apply')content=await applyPage();
  else if(p==='/app/inbox')content=await inboxPage();
  else if(p==='/submissions/status')content=await statusPage();
  else content=notFound();
 }catch(e){content='<main>'+pageHero('System','CuratorOS hit an error.','The public shell is live, but this data surface could not load right now.')+'<section class="section"><div class="shell"><div class="notice error">'+esc(e.message||String(e))+'</div></div></section></main>'}
 root.innerHTML=chrome(content);bind();
}

function navigate(href){history.pushState({},'',href);render()}
function bind(){
 document.querySelectorAll('[data-link]').forEach(a=>a.addEventListener('click',e=>{const href=a.getAttribute('href');if(href&&href.startsWith('/')){e.preventDefault();navigate(href)}}));
 document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;render()}));
 const hero=document.getElementById('hero-go');if(hero)hero.onclick=()=>{const q=document.getElementById('hero-search').value.trim();if(q)navigate('/submit?q='+encodeURIComponent(q))};
 const grid=document.getElementById('playlist-grid');if(grid)document.querySelectorAll('[data-genre]').forEach(btn=>btn.onclick=async()=>{document.querySelectorAll('[data-genre]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const g=btn.dataset.genre;const ps=(await getPlaylists()).filter(p=>p.lifecycle_state==='active'&&p.verification_status==='verified'&&(!g||[p.primary_genre,...(p.secondary_genres||[])].includes(g)));grid.innerHTML=ps.map(playlistCard).join('');bind()});
 bindSubmit();bindTools();bindAuth();
}
function bindSubmit(){
 const s=document.getElementById('submit-search');if(s)s.onclick=async()=>{const q=document.getElementById('submit-q').value.trim();const box=document.getElementById('submit-results');if(!q)return;box.innerHTML='<div class="provenance">Searching…</div>';const r=await fetch('/api/track?q='+encodeURIComponent(q));const b=await r.json();const results=b.track?[b.track]:(b.results||[]);box.innerHTML=results.length?results.map((t,i)=>'<button class="route-card choose-track" data-index="'+i+'"><span>♪</span><span><strong>'+esc(t.title)+'</strong><br><small>'+esc(t.artist_name)+'</small></span><span>Choose →</span></button>').join(''):'<div class="notice error">No track found. Try the exact Spotify track URL.</div>';state.submit.results=results;document.querySelectorAll('.choose-track').forEach(btn=>btn.onclick=()=>{state.submit.track=results[Number(btn.dataset.index)];state.submit.step=2;render()})};
 const genre=document.getElementById('submit-genre');if(genre)genre.onchange=()=>{state.submit.genre=genre.value;state.submit.moods=[];state.submit.selected=[];render()};
 document.querySelectorAll('#submit-moods [data-mood]').forEach(b=>b.onclick=()=>{const m=b.dataset.mood;state.submit.moods=state.submit.moods.includes(m)?state.submit.moods.filter(x=>x!==m):[...state.submit.moods,m].slice(0,8);render()});
 document.querySelectorAll('[data-route]').forEach(c=>c.onchange=()=>{const x=c.dataset.route;state.submit.selected=c.checked?[...new Set([...state.submit.selected,x])].slice(0,8):state.submit.selected.filter(v=>v!==x);render()});
 const next=document.getElementById('submit-next');if(next)next.onclick=()=>{state.submit.step=3;render()};
 const final=document.getElementById('submit-final');if(final)final.onclick=async()=>{const artist=document.getElementById('submit-artist').value.trim(),email=document.getElementById('submit-email').value.trim(),notes=document.getElementById('submit-notes').value.trim(),msg=document.getElementById('submit-message');if(!artist||!email.includes('@')){msg.innerHTML='<div class="notice error">Artist name and a valid email are required.</div>';return}final.disabled=true;final.textContent='Submitting…';const t=state.submit.track;const r=await fetch('/api/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({release_state:'released',artist_name:artist,email,song_title:t.title,spotify_url:t.spotify_url,release_date:t.release_date?String(t.release_date).slice(0,10):null,genre:state.submit.genre,moods:state.submit.moods,comparable_artists:[],is_explicit:Boolean(t.is_explicit),notes,preferred_playlists:state.submit.selected,network_opt_in:true,route_mode:'selected_only',source_surface:'curatoros',identified_track:t,artwork_url:t.artwork_url,website:''})});const b=await r.json();if(!r.ok){msg.innerHTML='<div class="notice error">'+esc(b.message||b.error||'Submission failed')+'</div>';final.disabled=false;final.textContent='Submit to selected playlists';return}msg.innerHTML='<div class="notice"><strong>Submission created.</strong><br>BVSS routes: '+esc(b.routed_to?.bvss??0)+' · Independent routes: '+esc(b.routed_to?.partner_curators??0)+'<br><a data-link href="/submissions/status?token='+esc(b.status_token)+'">Track every decision →</a></div>';bind()}};
}
function bindTools(){
 document.querySelectorAll('#tool-moods [data-mood],#gm-moods [data-mood]').forEach(b=>b.onclick=()=>{b.classList.toggle('active');if(b.closest('#gm-moods')){const g=document.getElementById('gm-genre').value;const ms=[...document.querySelectorAll('#gm-moods .active')].map(x=>x.dataset.mood);document.getElementById('gm-output').textContent=(g||'Choose a genre')+(ms.length?' · '+ms.join(' · '):'')}});
 const rec=document.getElementById('tool-recognize');if(rec)rec.onclick=async()=>{const q=document.getElementById('tool-track').value.trim(),m=document.getElementById('tool-message');const r=await fetch('/api/track?q='+encodeURIComponent(q));const b=await r.json();const t=b.track||(b.results||[])[0];m.textContent=t?'Recognized '+t.title+' — '+t.artist_name:'No track found. Try the Spotify URL.';runFitTool()};
 const tg=document.getElementById('tool-genre');if(tg)tg.onchange=runFitTool;document.querySelectorAll('#tool-moods [data-mood]').forEach(b=>b.addEventListener('click',runFitTool));
 async function runFitTool(){const box=document.getElementById('fit-results'),g=document.getElementById('tool-genre')?.value;if(!box||!g)return;const ms=[...document.querySelectorAll('#tool-moods .active')].map(x=>x.dataset.mood);const ps=(await getPlaylists()).filter(p=>p.submission_status==='open').map(p=>({p,f:fit(p,g,ms)})).filter(x=>x.f.strength>0).sort((a,b)=>b.f.strength-a.f.strength).slice(0,8);box.innerHTML=ps.map(({p,f})=>'<div class="route-card"><span>→</span><div><h3>'+esc(p.canonical_name)+'</h3>'+f.reasons.map(x=>'<div class="provenance">'+esc(x)+'</div>').join('')+'</div>'+fitBadge(f.band)+'</div>').join('')}
 const safety=document.getElementById('safety-playlist');if(safety)safety.onchange=async()=>{const p=(await getPlaylists()).find(x=>x.slug===safety.value),box=document.getElementById('safety-result');if(!p)return;const age=p.follower_count_observed_at?Math.round((Date.now()-new Date(p.follower_count_observed_at).getTime())/86400000):null;box.innerHTML='<h3>'+esc(p.canonical_name)+'</h3><p>Claim: <strong>'+esc(p.verification_status)+'</strong><br>Submissions: <strong>'+esc(p.submission_status)+'</strong><br>Follower measurement age: <strong>'+(age==null?'Unavailable':age+' days')+'</strong><br>Editorial update: <strong>'+date(p.last_editorial_update_at)+'</strong></p><p class="provenance">No single signal proves bot activity. Unknown data remains unknown.</p>'};
 const pitch=document.getElementById('pitch-go');if(pitch)pitch.onclick=async()=>{const title=document.getElementById('pitch-track').value.trim(),pslug=document.getElementById('pitch-playlist').value,p=(await getPlaylists()).find(x=>x.slug===pslug),out=document.getElementById('pitch-output');if(!title||!p){out.textContent='Add the track and choose a playlist first.';return}out.textContent='Hi — I’m pitching '+title+'. It sits in the '+p.primary_genre+' lane, which seems aligned with '+p.canonical_name+'. Thanks for listening — no placement expectation, just sharing because the fit looks relevant.'};
 const copy=document.getElementById('pitch-copy');if(copy)copy.onclick=()=>navigator.clipboard.writeText(document.getElementById('pitch-output').textContent);
 const ready=document.getElementById('ready-go');if(ready)ready.onclick=()=>{const vals=[document.getElementById('ready-track').value.trim(),document.getElementById('ready-date').value,document.getElementById('ready-genre').value,document.getElementById('ready-pitch').value];const score=vals.filter(Boolean).length;document.getElementById('ready-score').textContent=score+'/4 essentials ready';document.getElementById('ready-output').textContent=score===4?'Ready for a fit check and targeted submission.':'Complete the missing basics before pitching.'};
}
function bindAuth(){
 const signIn=document.getElementById('auth-signin'),signUp=document.getElementById('auth-signup');
 async function auth(kind){const email=document.getElementById('auth-email').value,password=document.getElementById('auth-password').value,msg=document.getElementById('auth-message');const r=kind==='signin'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});msg.innerHTML='<div class="notice '+(r.error?'error':'')+'" style="margin-top:14px">'+esc(r.error?.message||(kind==='signup'?'Account created. Confirm email if required, then sign in.':'Signed in.'))+'</div>';if(!r.error){state.session=r.data.session||state.session;setTimeout(render,300)}}
 if(signIn)signIn.onclick=()=>auth('signin');if(signUp)signUp.onclick=()=>auth('signup');
 const apply=document.getElementById('apply-submit');if(apply)apply.onclick=async()=>{const body={action:'apply',display_name:document.getElementById('apply-name').value.trim(),handle:document.getElementById('apply-handle').value.trim(),contact_email:state.session.user.email,bio:document.getElementById('apply-bio').value.trim(),genres:document.getElementById('apply-genres').value.split(',').map(x=>x.trim()).filter(Boolean),moods:[]};const r=await fetch('/api/curator',{method:'POST',headers:{Authorization:'Bearer '+state.session.access_token,'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json();document.getElementById('apply-message').innerHTML='<div class="notice '+(r.ok?'':'error')+'" style="margin-top:14px">'+esc(r.ok?'Application saved.':b.error||'Could not save')+'</div>';if(r.ok)setTimeout(render,500)};
 const claim=document.getElementById('claim-add');if(claim)claim.onclick=async()=>{const body={action:'add_playlist',spotify_url:document.getElementById('claim-url').value.trim(),canonical_name:document.getElementById('claim-name').value.trim(),primary_genre:document.getElementById('claim-genre').value.trim(),secondary_genres:[],moods:[],description:'',curation_philosophy:'Independent curator on CuratorOS.',submission_criteria:'Tracks are reviewed independently. Placement is never guaranteed.'};const r=await fetch('/api/curator',{method:'POST',headers:{Authorization:'Bearer '+state.session.access_token,'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json();document.getElementById('claim-message').innerHTML='<div class="notice '+(r.ok?'':'error')+'" style="margin-top:14px">'+esc(r.ok?'Verification code: '+b.claim.verification_code:(b.error||'Could not add playlist'))+'</div>'};
 document.querySelectorAll('.curator-decision').forEach(btn=>btn.onclick=async()=>{const decision=btn.dataset.decision,body={action:'review_route',route_id:btn.dataset.route,decision,reasons:decision==='reject'?['not_my_genre_lane']:[],hold_until:decision==='hold'?new Date(Date.now()+7*86400000).toISOString():null,notes:null};btn.disabled=true;const r=await fetch('/api/curator',{method:'POST',headers:{Authorization:'Bearer '+state.session.access_token,'Content-Type':'application/json'},body:JSON.stringify(body)});btn.disabled=false;if(r.ok)render();else{const b=await r.json();alert(b.error||'Decision not saved')}});
}
window.addEventListener('popstate',render);
supabase.auth.onAuthStateChange((_e,s)=>{state.session=s});
render();