create extension if not exists pgcrypto;

create table if not exists public.bvss_playlists (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  spotify_playlist_id text not null unique,
  spotify_uri text not null unique,
  spotify_url text not null,
  canonical_name text not null,
  subtitle text not null default '',
  description text not null default '',
  cover_asset_url text,
  primary_genre text not null,
  secondary_genres text[] not null default '{}',
  moods text[] not null default '{}',
  activities text[] not null default '{}',
  seo_keywords text[] not null default '{}',
  anchor_artists text[] not null default '{}',
  target_track_count integer not null default 70 check (target_track_count between 10 and 500),
  current_track_count integer check (current_track_count is null or current_track_count >= 0),
  current_follower_count bigint check (current_follower_count is null or current_follower_count >= 0),
  follower_count_source text,
  follower_count_observed_at timestamptz,
  spotify_created_date date,
  spotify_last_synced_at timestamptz,
  last_editorial_update_at timestamptz,
  public_status text not null default 'public' check (public_status in ('draft','public','private')),
  submission_status text not null default 'open' check (submission_status in ('open','paused','closed')),
  update_cadence text not null default 'weekly',
  middle_child_eligible boolean not null default true,
  subflower_eligible boolean not null default false,
  website_status text not null default 'published' check (website_status in ('draft','published','hidden')),
  lifecycle_state text not null default 'active' check (lifecycle_state in ('active','experimental','archived')),
  curation_philosophy text not null default '',
  submission_criteria text not null default '',
  display_order integer not null default 100,
  source_metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(source_metadata)='object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bvss_playlist_metric_snapshots (
  id uuid primary key default gen_random_uuid(),
  playlist_id uuid not null references public.bvss_playlists(id) on delete cascade,
  metric_date date not null,
  followers bigint check (followers is null or followers >= 0),
  track_count integer check (track_count is null or track_count >= 0),
  source text not null,
  source_ref text,
  raw_data jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null default now(),
  unique (playlist_id, metric_date, source)
);
create index if not exists bvss_playlist_metric_playlist_date_idx on public.bvss_playlist_metric_snapshots(playlist_id,metric_date desc);

create table if not exists public.bvss_playlist_tracks (
  id uuid primary key default gen_random_uuid(),
  playlist_id uuid not null references public.bvss_playlists(id) on delete cascade,
  spotify_track_id text not null,
  track_name text,
  artists text[] not null default '{}',
  isrc text,
  spotify_url text,
  artwork_url text,
  position integer check (position is null or position >= 0),
  added_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  is_active boolean not null default true,
  source text not null default 'spotify',
  source_metadata jsonb not null default '{}'::jsonb,
  unique (playlist_id, spotify_track_id)
);
create index if not exists bvss_playlist_tracks_active_idx on public.bvss_playlist_tracks(playlist_id,is_active,position);

create table if not exists public.bvss_playlist_track_events (
  id uuid primary key default gen_random_uuid(),
  playlist_id uuid not null references public.bvss_playlists(id) on delete cascade,
  spotify_track_id text not null,
  event_type text not null check (event_type in ('added','removed','moved','metadata_updated')),
  old_position integer,
  new_position integer,
  event_at timestamptz not null default now(),
  source text not null,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.bvss_web_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('playlist_view','spotify_click','submit_start','submit_complete')),
  playlist_id uuid references public.bvss_playlists(id) on delete set null,
  path text not null,
  referrer_host text,
  session_hash text,
  utm jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);
create index if not exists bvss_web_events_playlist_time_idx on public.bvss_web_events(playlist_id,occurred_at desc);

create table if not exists public.bvss_search_metrics (
  id bigint generated by default as identity primary key,
  metric_date date not null,
  playlist_id uuid references public.bvss_playlists(id) on delete cascade,
  page_path text not null,
  query text,
  clicks integer not null default 0 check (clicks >= 0),
  impressions integer not null default 0 check (impressions >= 0),
  ctr numeric(8,6) check (ctr is null or (ctr >= 0 and ctr <= 1)),
  position numeric(8,3) check (position is null or position >= 0),
  source text not null default 'google_search_console',
  source_metadata jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null default now()
);
create unique index if not exists bvss_search_metrics_unique on public.bvss_search_metrics(
  metric_date,
  coalesce(playlist_id,'00000000-0000-0000-0000-000000000000'::uuid),
  page_path,
  coalesce(query,''),
  source
);

create table if not exists public.bvss_submissions (
  id uuid primary key default gen_random_uuid(),
  artist_name text not null check (char_length(trim(artist_name)) between 1 and 160),
  email text not null check (position('@' in email) > 1),
  song_title text not null check (char_length(trim(song_title)) between 1 and 200),
  spotify_url text not null,
  spotify_track_id text,
  release_date date,
  genre text not null check (char_length(trim(genre)) between 1 and 120),
  moods text[] not null default '{}',
  comparable_artists text[] not null default '{}',
  is_explicit boolean not null default false,
  notes text check (notes is null or char_length(notes) <= 4000),
  preferred_playlist_ids uuid[] not null default '{}',
  status text not null default 'pending' check (status in ('pending','in_review','hold','accepted','rejected','withdrawn')),
  submission_source text not null default 'bvssfvm.com',
  duplicate_fingerprint text generated always as (
    md5(lower(trim(email)) || '|' || coalesce(spotify_track_id, lower(trim(spotify_url))))
  ) stored,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (duplicate_fingerprint)
);
create index if not exists bvss_submissions_status_time_idx on public.bvss_submissions(status,submitted_at desc);

create table if not exists public.bvss_submission_matches (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.bvss_submissions(id) on delete cascade,
  playlist_id uuid not null references public.bvss_playlists(id) on delete cascade,
  score integer not null check (score between 0 and 100),
  reasons jsonb not null default '[]'::jsonb,
  rank integer not null check (rank > 0),
  matcher_version text not null default 'deterministic-v1',
  created_at timestamptz not null default now(),
  unique (submission_id, playlist_id)
);
create index if not exists bvss_submission_matches_rank_idx on public.bvss_submission_matches(submission_id,rank);

create table if not exists public.bvss_submission_reviews (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.bvss_submissions(id) on delete cascade,
  decision text not null check (decision in ('hold','accept','reject')),
  playlist_id uuid references public.bvss_playlists(id) on delete set null,
  reviewer_id uuid references auth.users(id) on delete set null,
  reviewer_label text,
  target_position integer check (target_position is null or target_position > 0),
  rotation_notes text,
  review_notes text,
  reviewed_at timestamptz not null default now()
);

create table if not exists public.bvss_playlist_placements (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid references public.bvss_submissions(id) on delete set null,
  playlist_id uuid not null references public.bvss_playlists(id) on delete cascade,
  spotify_track_id text,
  placed_at timestamptz not null default now(),
  target_position integer,
  actual_position integer,
  removed_at timestamptz,
  notes text
);
create index if not exists bvss_placements_playlist_idx on public.bvss_playlist_placements(playlist_id,placed_at desc);

create table if not exists public.bvss_integrations (
  provider text primary key,
  status text not null default 'not_configured' check (status in ('not_configured','ready','connected','degraded','disabled')),
  capabilities text[] not null default '{}',
  last_sync_at timestamptz,
  notes text,
  configuration jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.bvss_sync_runs (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  sync_type text not null,
  status text not null check (status in ('started','completed','partial','failed')),
  playlist_id uuid references public.bvss_playlists(id) on delete cascade,
  requested_at timestamptz not null default now(),
  completed_at timestamptz,
  records_seen integer not null default 0,
  records_written integer not null default 0,
  error_summary text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.bvss_admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('admin','reviewer')),
  created_at timestamptz not null default now()
);

alter table public.bvss_playlists enable row level security;
alter table public.bvss_playlist_metric_snapshots enable row level security;
alter table public.bvss_playlist_tracks enable row level security;
alter table public.bvss_playlist_track_events enable row level security;
alter table public.bvss_web_events enable row level security;
alter table public.bvss_search_metrics enable row level security;
alter table public.bvss_submissions enable row level security;
alter table public.bvss_submission_matches enable row level security;
alter table public.bvss_submission_reviews enable row level security;
alter table public.bvss_playlist_placements enable row level security;
alter table public.bvss_integrations enable row level security;
alter table public.bvss_sync_runs enable row level security;
alter table public.bvss_admin_users enable row level security;

drop policy if exists "bvss_public_playlists_select" on public.bvss_playlists;
create policy "bvss_public_playlists_select" on public.bvss_playlists
for select to anon, authenticated
using (public_status='public' and website_status='published' and lifecycle_state <> 'archived');

drop policy if exists "bvss_public_tracks_select" on public.bvss_playlist_tracks;
create policy "bvss_public_tracks_select" on public.bvss_playlist_tracks
for select to anon, authenticated
using (
  is_active and exists (
    select 1 from public.bvss_playlists p
    where p.id=playlist_id and p.public_status='public' and p.website_status='published' and p.lifecycle_state <> 'archived'
  )
);

create or replace function public.bvss_is_admin()
returns boolean language sql stable security definer set search_path=public
as $$
  select exists(select 1 from public.bvss_admin_users a where a.user_id=auth.uid());
$$;

create policy "bvss_admin_playlists_all" on public.bvss_playlists for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy "bvss_admin_metrics_all" on public.bvss_playlist_metric_snapshots for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy "bvss_admin_tracks_all" on public.bvss_playlist_tracks for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy "bvss_admin_events_all" on public.bvss_playlist_track_events for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy "bvss_admin_web_all" on public.bvss_web_events for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy "bvss_admin_search_all" on public.bvss_search_metrics for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy "bvss_admin_submissions_all" on public.bvss_submissions for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy "bvss_admin_matches_all" on public.bvss_submission_matches for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy "bvss_admin_reviews_all" on public.bvss_submission_reviews for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy "bvss_admin_placements_all" on public.bvss_playlist_placements for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy "bvss_admin_integrations_all" on public.bvss_integrations for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy "bvss_admin_sync_all" on public.bvss_sync_runs for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy "bvss_admin_users_select" on public.bvss_admin_users for select to authenticated
using (user_id=auth.uid());

grant select on public.bvss_playlists, public.bvss_playlist_tracks to anon, authenticated;

create or replace function public.bvss_touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end $$;

drop trigger if exists bvss_playlists_touch on public.bvss_playlists;
create trigger bvss_playlists_touch before update on public.bvss_playlists
for each row execute function public.bvss_touch_updated_at();

drop trigger if exists bvss_submissions_touch on public.bvss_submissions;
create trigger bvss_submissions_touch before update on public.bvss_submissions
for each row execute function public.bvss_touch_updated_at();

create or replace view public.bvss_playlist_daily_rollup as
select
  p.id as playlist_id,
  p.slug,
  p.canonical_name,
  p.spotify_playlist_id,
  p.current_follower_count,
  p.current_track_count,
  p.last_editorial_update_at,
  p.spotify_last_synced_at,
  (
    select s.followers from public.bvss_playlist_metric_snapshots s
    where s.playlist_id=p.id and s.metric_date <= current_date-1 and s.followers is not null
    order by s.metric_date desc, s.observed_at desc limit 1
  ) as followers_1d_ago,
  (
    select s.followers from public.bvss_playlist_metric_snapshots s
    where s.playlist_id=p.id and s.metric_date <= current_date-7 and s.followers is not null
    order by s.metric_date desc, s.observed_at desc limit 1
  ) as followers_7d_ago,
  (
    select s.followers from public.bvss_playlist_metric_snapshots s
    where s.playlist_id=p.id and s.metric_date <= current_date-30 and s.followers is not null
    order by s.metric_date desc, s.observed_at desc limit 1
  ) as followers_30d_ago,
  (
    select s.followers from public.bvss_playlist_metric_snapshots s
    where s.playlist_id=p.id and s.metric_date <= current_date-90 and s.followers is not null
    order by s.metric_date desc, s.observed_at desc limit 1
  ) as followers_90d_ago,
  (select count(*) from public.bvss_submissions s where p.id=any(s.preferred_playlist_ids) and s.status in ('pending','in_review','hold')) as submissions_waiting,
  (select count(*) from public.bvss_playlist_placements pl where pl.playlist_id=p.id and pl.removed_at is null) as active_placements,
  (select count(*) from public.bvss_web_events e where e.playlist_id=p.id and e.event_name='playlist_view' and e.occurred_at >= now()-interval '30 days') as pageviews_30d,
  (select count(*) from public.bvss_web_events e where e.playlist_id=p.id and e.event_name='spotify_click' and e.occurred_at >= now()-interval '30 days') as spotify_clicks_30d,
  (select coalesce(sum(sm.impressions),0) from public.bvss_search_metrics sm where sm.playlist_id=p.id and sm.metric_date>=current_date-30) as search_impressions_30d,
  (select coalesce(sum(sm.clicks),0) from public.bvss_search_metrics sm where sm.playlist_id=p.id and sm.metric_date>=current_date-30) as search_clicks_30d
from public.bvss_playlists p;

insert into public.bvss_integrations(provider,status,capabilities,notes) values
('spotify','ready',array['playlist identity','playlist links','owned playlist discovery'],'Canonical identity source. Current public API availability for follower totals is limited, so do not synthesize follower counts.'),
('spotontrack','not_configured',array['playlist follower history','playlist audience'],'Candidate primary follower-history feed if API access is available.'),
('chartmetric','not_configured',array['playlist monitoring','playlist changes','competitive intelligence'],'Powerful monitoring/competitive source; likely overlaps with internal snapshots once the network matures.'),
('soundcharts','not_configured',array['playlist audience','artist downstream performance','playlist discovery'],'Best fit for artist-side downstream measurement and cross-checking playlist audience data.'),
('soundiiz','not_configured',array['playlist backup','cross-DSP sync'],'Operational sync/backup; not a metrics source of truth.'),
('google_search_console','not_configured',array['search impressions','search clicks','queries','average position'],'Authoritative source for organic search performance once connected.'),
('bvss_first_party','ready',array['pageviews','spotify outbound clicks','submission events'],'BVSS-owned event stream; no vanity-score layer.')
on conflict(provider) do update set capabilities=excluded.capabilities,notes=excluded.notes,updated_at=now();
