create table if not exists public.bvss_media_uploads (
  id uuid primary key default gen_random_uuid(),
  object_path text not null unique,
  original_filename text,
  content_type text,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes >= 0),
  requester_hash text,
  status text not null default 'pending',
  submission_id uuid references public.bvss_submissions(id) on delete set null,
  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  expires_at timestamptz not null default (now() + interval '24 hours')
);
do $$ begin
  if not exists (select 1 from pg_constraint where conname='bvss_media_uploads_status_check') then
    alter table public.bvss_media_uploads add constraint bvss_media_uploads_status_check
      check (status in ('pending','claimed','expired','deleted'));
  end if;
end $$;
create index if not exists bvss_media_uploads_cleanup_idx on public.bvss_media_uploads(status,expires_at);
create index if not exists bvss_media_uploads_requester_idx on public.bvss_media_uploads(requester_hash,created_at desc);

create table if not exists public.bvss_public_rate_limits (
  id bigint generated by default as identity primary key,
  requester_hash text not null,
  action text not null,
  occurred_at timestamptz not null default now()
);
create index if not exists bvss_public_rate_limits_lookup_idx
  on public.bvss_public_rate_limits(requester_hash,action,occurred_at desc);

alter table public.bvss_media_uploads enable row level security;
alter table public.bvss_public_rate_limits enable row level security;

create policy bvss_admin_media_uploads_all on public.bvss_media_uploads for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());
create policy bvss_admin_rate_limits_all on public.bvss_public_rate_limits for all to authenticated
using (public.bvss_is_admin()) with check (public.bvss_is_admin());

update storage.buckets
set allowed_mime_types=array[
  'audio/mpeg','audio/wav','audio/x-wav','audio/wave','audio/flac','audio/x-flac',
  'audio/mp4','audio/x-m4a','audio/aac'
]
where id='bvss-submission-audio';
